### ISSUE TITLE
Making user attributes configurable

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/carbon-auth#112]
They are hardcoded in [DB script](https://github.com/wso2/carbon-auth/blob/v1.0.32/features/auth-features/org.wso2.carbon.auth.core.feature/resources/dbscripts/um/h2.sql#L85-L96). No way of adding new attributes.

**Comment by malinthaprasan** [comment]
Fixed in https://github.com/wso2/carbon-auth/pull/110/commits/c07b989d8479097e64cad0b45788de5854664689

**Comment by malinthaprasan** [comment]
Attributes can be configured in deployment.yaml.

wso2.carbon.auth.user.store -> attributes

```
wso2.carbon.auth.user.store:
  connectorType: JDBC
  hashAlgo: SHA256
  iterationCount: 4096
  jdbcProperties:
    dataSource: WSO2_UM_DB
  keyLength: 256
  ldapProperties:
    ldap.ConnectionName: cn=admin,dc=example,dc=org
    ldap.GroupEntryObjectClass: groupOfNames
    ldap.UserNameSearchFilter: (&amp;(objectClass=person)(uid=?))
    ldap.ConnectionURL: ldap://localhost:389
    ldap.InitialContextFactory: com.sun.jndi.ldap.LdapCtxFactory
    ldap.connectorClass: org.wso2.carbon.auth.user.store.connector.ldap.LDAPUserStoreConnector
    ldap.GroupSearchBase: ou=Groups,dc=example,dc=org
    ldap.ConnectionPassword: admin
    ldap.UserNameAttribute: uid
    ldap.GroupSearchFilter: (&amp;(objectClass=groupOfNames)(cn=?))
    ldap.UserEntryObjectClass: identityPerson
    ldap.GroupAttribute: cn
    ldap.SecurityAuthentication: simple
    ldap.UserNameListFilter: (objectClass=person)
    ldap.GroupListFilter: (objectClass=groupOfNames)
    ldap.UserSearchBase: ou=Users,dc=example,dc=org
  readOnly: false
  superUser: admin
  superUserPass: admin
  attributes:
  - attributeName: id
    attributeUri: urn:ietf:params:scim:schemas:core:2.0:id
    displayName: ID
    regex: .*
    required: true
    uniqueness: GLOBAL
  - attributeName: created
    attributeUri: urn:ietf:params:scim:schemas:core:2.0:meta.created
    displayName: Created Time
    regex: .*
    required: true
    uniqueness: NONE
  - attributeName: lastModified
    attributeUri: urn:ietf:params:scim:schemas:core:2.0:meta.lastModified
    displayName: Last Modified Time
    regex: .*
    required: true
    uniqueness: NONE
  - attributeName: resourceType
    attributeUri: urn:ietf:params:scim:schemas:core:2.0:meta.resourceType
    displayName: Resource Type
    regex: .*
    required: true
    uniqueness: NONE
  - attributeName: userName
    attributeUri: urn:ietf:params:scim:schemas:core:2.0:User:userName
    displayName: User Name
    regex: .*
    required: true
    uniqueness: SERVER
  - attributeName: displayName
    attributeUri: urn:ietf:params:scim:schemas:core:2.0:User:displayName
    displayName: Display Name
    regex: .*
    required: false
    uniqueness: NONE
  - attributeName: password
    attributeUri: urn:ietf:params:scim:schemas:core:2.0:User:password
    displayName: Password
    regex: .*
    required: true
    uniqueness: NONE
  - attributeName: familyName
    attributeUri: urn:ietf:params:scim:schemas:core:2.0:User:name.familyName
    displayName: Family Name
    regex: .*
    required: false
    uniqueness: NONE
  - attributeName: givenName
    attributeUri: urn:ietf:params:scim:schemas:core:2.0:User:name.givenName
    displayName: Given Name
    regex: .*
    required: false
    uniqueness: NONE
  - attributeName: primaryEmail
    attributeUri: urn:ietf:params:scim:schemas:core:2.0:User:emails.primary
    displayName: Primary Email
    regex: .*
    required: false
    uniqueness: SERVER
  - attributeName: workEmail
    attributeUri: urn:ietf:params:scim:schemas:core:2.0:User:emails.work
    displayName: Work Email
    regex: .*
    required: false
    uniqueness: NONE
  - attributeName: homeEmail
    attributeUri: urn:ietf:params:scim:schemas:core:2.0:User:emails.home
    displayName: Home Email
    regex: .*
    required: false
    uniqueness: NONE
  - attributeName: displayName
    attributeUri: urn:ietf:params:scim:schemas:core:2.0:Group:displayName
    displayName: Group Display Name
    regex: .*
    required: false
    uniqueness: SERVER
```
